### ISSUE TITLE
[Question] Comparison with xwmx/nb?

### ISSUE THREAD

**Issue by nbCloud91** [RyanGreenup/cadmus#19]
There is this shell script https://github.com/xwmx/nb which tries to do something similar. The use cases may be slightly different, but there could be some overlap.
Currently, I am looking for a set of tools with functionality similar to org-mode+helm-recoll+org-roam+org-pdftools (with this we have org-mode notes on PDFs, with full-text search from recoll and roam like back-linked zettel system) but not tied to emacs. In my search for it, I came across cadmus and xwmx's nb. Both are quite well-made, but none of them have all the features I need. The fzf/skim+recoll search interface of cadmus is better suited to my needs compared to ag/rg/grep based search of nb.
But, neither in cadmus nor nb, I can find any integration for making notes associated with arbitrary pdf files and such (the notes linking back to the specific location on the pdf preferably). There is an [open issue](https://github.com/xwmx/nb/issues/54) over at nb for this though. Another plus for nb is that it handles org, markdown and LaTeX notes, so I can directly use my earlier org notes without converting them to markdown first.
I am undecided on what to choose, or whether it'd be wise to use both of these tools. Can we expect some features like, choice to use org markup for notes and linking to arbitrary pdf files, to be implemented in cadmus in the future?

**Comment by RyanGreenup** [comment]
Hey, sorry I've been ~~really~~ extremely busy with school.

### comparison
So off the top of my head, having not used it, I would say that `nb` would be the more fleshed out project. What `cadmus` is, essentially, is bunch of shell scripts that I found myself using all the time and I thought others would like to use them as well.

### interface

So good news, the fzf/skim+recoll stuff is totally agnostic and you can use it with `org-mode` (which I do) or anything else you like, you shouldn't even need to use all of cadmus, I tried to write it all in a way that others could take the pieces that they liked and discard what they didn't, so if you just want to implement [the search](https://github.com/RyanGreenup/cadmus/blob/master/bin/NoteRecollSearch.sh) and [the find](https://github.com/RyanGreenup/cadmus/blob/master/bin/NoteFind.sh) aspects it should be no issue at all, See also [here](https://ryangreenup.github.io/cadmus/find.html) and [here](https://ryangreenup.github.io/cadmus/search.html).

### Org

I actually do currently use `org` files as well as markdown with cadmus, my background is math and markdown implements latex so inconsistently that I just avoid it for anything like that. The tags aren't implemented but the find/search work great and that's all I use.

As an aside I catch myself using *Dokuwiki* more and more because it really is so convenient.

### Features

Yeah if there's features and stuff you want, just create seperate issues, worst case I'll be busy and instead I'll point you towards making a PR.

As a project I was gonna try and write cadmus as one tool all in `go`, swapping recoll for some a simpler search algorithm, that way it would be easier to use etc., but I've just been so busy.

### Choosing a tool

I still haven't found a forever-notetaking-tool, I'm gonna make a comparison of what i've tried on [a wiki](http://ryansnotes.org/dokuwiki/doku.php?id=note_taking_tools_and_wiki_software) one day <sup>TM</sup>, my advice would be to choose something agnostic that just uses text files (be it org, dokuwiki or markdown), I think using VSCode with [markdown memo](https://marketplace.visualstudio.com/items?itemName=svsool.markdown-memo), [markdown notes](https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes), [foam](https://foambubble.github.io/foam/) or [Dendron](https://dendron.so/) makes a lot of sense, it's all open source, works well enough and is compatible with all the shell scripts in cadmus that are reasonably easy to implement/understand.

That's pretty much what I do but I use Dokuwiki/Org-Mode as well because math in markdown is a pain in the ass.

Other considerations:


- Zettlr
- Joplin
  - The Sqlite search is inferior to Recoll, [see generally this blog post](https://partyondata.com/2009/07/06/a-comparison-of-open-source-search-engines-and-indexing-twitter/)
- WikiJS with Docker
  - Not bad, but a little clunky
- Dokuwiki
  - Fantastic, but a little slow and a different markup language
- Mediawiki
  - good, but dokuwiki is simpler and easier and there otherwise about the same.
- Notable
  - <sub>Not FOSS</sub>
    - does contribute open source libraries though so that's fair enough I guess.
  - YAML tags are a little annoying to work with
- Obsidian
  - Not FOSS

**Comment by nbCloud91** [comment]
Thanks for that detailed reply! My work requires mixing maths, code and taking notes on papers/articles. I've already looked at or tried most of the tools you mention. Joplin, it is a great project but I wanted something lighter. Zettlr, used it for a while, the early versions, maybe it's improved now. Dokuwiki, I have it installed and quite like it, I'd want to export my notes to it for reading, but it's not great for writing in, I have not yet tried the vim-to-dokuwiki workflows and plugins. Mediawiki is overkill for me. I also tried to use tiddlywiki a few times, it seems really sleek and featureful, but again I ended up not using it, it has certain limitations if you just use one single html file. I have dendron installed, did not really check it out (only time I use vscode is to run jupyter notebooks which is a much better experience than jupyterlab on browser). Notability and obsidian were not foss, plus even foss solutions comparable to obsidian(logseq is one) are overkill. Org mode+org-roam+helm+org-pdftools is great in that way, it is almost the perfect solution, except for the fact that I don't otherwise use Emacs. I don't care about editor tribalism, with evil we get modal vim like editing, buuut it is just that for all other kinds of work I tend to use vim anyway without even trying. The thing that really bothers me though is Emacs is on some occasions super slow. Which prompted me to search for alternatives.
 I will try to see if I can take bits and pieces from cadmus. Thanks again for sharing the scripts.

**Comment by nbCloud91** [comment]
Hey, I just came across this tool [neuron](https://neuron.zettel.page/philosophy). What I *especially* liked about the philosophy, is the focus on editor decoupling(it already has neovim/vim, emacs and vscode integrations). Despite all the goodies of org-roam, this editor lock in was one thing which always bothered me. Since you seem to be into FOSS note-taking solutions, thought you might be interested.

Edit: Sorry, I see that you have checked out neuron [already](http://ryansnotes.org/dokuwiki/doku.php?id=note_taking_tools_and_wiki_software), and you said you couldn't get it to work.

**Comment by RyanGreenup** [comment]
No thanks for posting, honestly, it's a good reminder to try it again.

I'm compiling a long list of things that I've tried.if you come across anything else at all post it here so I can throw it in my list..
